### ISSUE TITLE
[linux-port] Enable MacOS buildbots

### ISSUE THREAD

**Issue by ehsannas** [google/DirectXShaderCompiler#199]
Enable MacOS buildbots for the google/linux branch so we know where we stand.

**Comment by pow2clk** [comment]
I've started chipping away at this and I've discovered some peculiar differences between the Linux and Apple linkers. 

First of all, the `g_ThreadMallocTls` global in dxcsupport is included by both libdxcompiler and the dxc binary and both make use of it. (The same was true of the previous `g_ThreadMallocTlsIndex`. So the previous change isn't relevant). In the current Linux implementation, we just have one initialization of this from the `DxcInitThreadMalloc` call in `main()` from the dxc binary. If we attempt the same on Apple, when calls originating from code unique to libdxcompiler, the global is found to be uninitialized, causing an assert to fire. This is because of a fundamental difference with how Apple and Linux resolve global variables. Linux turns all references to such a shared global to the same one. Apple directs each reference to the source pertaining to the binary that the reference belongs to.

I made a simple test in the attached zip file. 
[dynlib.zip](https://github.com/google/DirectXShaderCompiler/files/2088295/dynlib.zip)

On Linux the output is:
> GLOBAL is 2
GLOBAL is 2
GLOBAL is 4
GLOBAL is 4

On MacOs:
> GLOBAL is 1
GLOBAL is 2
GLOBAL is 4
GLOBAL is 3

Possibly worth noting, even though I used clang for both of these, clang (and gcc) just use the system's default linker. So the compiler isn't really relevant.

As a result of this, I determined that the separate initialization provided by the explicit loading of libdxcompiler would resolve the issue. This gave me additional motivation to the effort to explicitly load libdxcompiler instead of linking on Unix OSes. I got that working on Linux, but discovered a problem on MacOs. The `DxcInitThreadMalloc` call mentioned previously calls `CoGetMalloc`. However, that function as currently written, uses `new` to allocate `IMalloc`, which tries to access the TLS, which isn't initialized because the `IMalloc` that would be placed there is currently being allocated. I was able to work around it by using a static variable though there is some ugliness to keep it from trying to delete itself when its refcount reaches zero. More interesting is that this didn't occur on Linux. That's because when not linked with the `main()` binary, none of these overrides seem to take effect. I haven't figured out why that is. I know that the ability to override the global `new` and `delete` operators is something of a special case. Perhaps there is a bug in the Linux linker.

These aren't the only problems, but they are perhaps the most in depth and I wanted to explain them fully somewhere other than the comment where I have space to do so. Any input on how best to resolve them is welcome.

**Comment by ehsannas** [comment]
Hey @pow2clk , Thanks for the detailed explanation. I'm sad to hear this; I was hoping there would be no/little friction going to MacOS. We haven't looked into enabling MacOS yet. And it is currently on the bottom of our priority list, as we've had no requests for it internally or externally (ok, maybe 1 "nice-to-have" external request). So don't be surprised if there is low/zero activity on this on my part. Having said that, it'd be great if we can have a solution that satisfies all three platforms.

I think @antiagainst has given it a try on his MacOS laptop, and I think he said he was able to get things working with a few minor changes?! My memory is fuzzy on that. Maybe he can comment on what he experienced...

**Comment by pow2clk** [comment]
I was able to get it building with a few minor changes. It's the running successfully that's the problem. I'm fairly near a solution that works for all three platforms though there is some roughness around the edges that I'm unsure about. As for what's holding Apple back right now it's something deep in SPIRV-Tools causing an assert to fire.

**Comment by ehsannas** [comment]
Thanks @pow2clk for the awesome work and getting things working on macOS!

**Comment by ehsannas** [comment]
I think we can close this now.
